services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: websocket-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: websocket-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
